// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./src/components/BaseHeader.vue')['default']
    DateFill: typeof import('./src/components/questionFill/DateFill.vue')['default']
    DateQuestion: typeof import('./src/components/questionType/DateQuestion.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HomeListItem: typeof import('./src/components/HomeListItem.vue')['default']
    HomeTag: typeof import('./src/components/HomeTag.vue')['default']
    InputFill: typeof import('./src/components/questionFill/InputFill.vue')['default']
    InputQuestion: typeof import('./src/components/questionType/InputQuestion.vue')['default']
    MultiSelectFill: typeof import('./src/components/questionFill/MultiSelectFill.vue')['default']
    MultiSelectQuestion: typeof import('./src/components/questionType/MultiSelectQuestion.vue')['default']
    PullSelectFill: typeof import('./src/components/questionFill/PullSelectFill.vue')['default']
    PullSelectQuestion: typeof import('./src/components/questionType/PullSelectQuestion.vue')['default']
    QuestionTemplate: typeof import('./src/components/questionType/QuestionTemplate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreFill: typeof import('./src/components/questionFill/ScoreFill.vue')['default']
    ScoreQuestion: typeof import('./src/components/questionType/ScoreQuestion.vue')['default']
    SingleSelectFill: typeof import('./src/components/questionFill/SingleSelectFill.vue')['default']
    SingleSelectQuestion: typeof import('./src/components/questionType/SingleSelectQuestion.vue')['default']
    TimeFill: typeof import('./src/components/questionFill/TimeFill.vue')['default']
    TimeQuestion: typeof import('./src/components/questionType/TimeQuestion.vue')['default']
  }
}

export {}
